In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
'''
1. 전국도시공원정보 표준데이터 파일을 읽고 다음에 답하세요. [40]
1) 공원명, 소재지지번주소, 공원면적 컬럼만 선택해서 데이터 프레임을 만드세요.
2) 경기도 데이터만 추출하세요.
3) 소재지지번주소에서 시군구(예, 이천시, 양평군, 수원시 장안구)를 추출해서   시군구 컬럼을 만드세요.
4) 시군구 별로 공원면적의 합을 구하세요.
'''

'\n1. 전국도시공원정보 표준데이터 파일을 읽고 다음에 답하세요. [40]\n1) 공원명, 소재지지번주소, 공원면적 컬럼만 선택해서 데이터 프레임을 만드세요.\n2) 경기도 데이터만 추출하세요.\n3) 소재지지번주소에서 시군구(예, 이천시, 양평군, 수원시 장안구)를 추출해서   시군구 컬럼을 만드세요.\n4) 시군구 별로 공원면적의 합을 구하세요.\n'

In [3]:
# 1) 공원명, 소재지지번주소, 공원면적 컬럼만 선택해서 데이터 프레임을 만드세요.
gpark = pd.read_csv('../04.지도시각화/data/경기도도시공원정보표준데이터.csv', encoding='euc-kr')
gpark.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17525 entries, 0 to 17524
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   관리번호          17525 non-null  object
 1   공원명           17525 non-null  object
 2   공원구분          17525 non-null  object
 3   소재지도로명주소      3692 non-null   object
 4   소재지지번주소       17335 non-null  object
 5   위도            17513 non-null  float64
 6   경도            17514 non-null  float64
 7   공원면적          17525 non-null  float64
 8   공원보유시설(운동시설)  4821 non-null   object
 9   공원보유시설(유희시설)  6200 non-null   object
 10  공원보유시설(편익시설)  4842 non-null   object
 11  공원보유시설(교양시설)  805 non-null    object
 12  공원보유시설(기타시설)  2577 non-null   object
 13  지정고시일         14451 non-null  object
 14  관리기관명         16033 non-null  object
 15  전화번호          16343 non-null  object
 16  데이터기준일자       17525 non-null  object
 17  제공기관코드        17525 non-null  object
 18  제공기관명         17525 non-null  object
dtypes: float64(3), object(16)
memory usage: 2.5+ MB

In [4]:
gp = gpark[['공원명','소재지지번주소' ,'공원면적']]
gp.head(110).tail(10)

         공원명                   소재지지번주소      공원면적
100       공원      경상북도 구미시 진평동 644-7번지     992.0
101     소소공원     경상북도 구미시 공단동 297-25번지    1223.0
102     화개공원  경상북도 구미시 고아읍 이례리 산6번지 일원   13063.0
103     양지공원    경상북도 구미시 신평동 6-38번지 일원   56148.0
104    꽃동산공원     경상북도 구미시 도량동 산25번지 일원  750000.0
105     중앙공원     경상북도 구미시 광평동 산57번지 일원  266534.0
106     오태공원      경상북도 구미시 임은동 산7번지 일원  318154.6
107  무등어린이공원        광주광역시 북구 두암동 595-5    1747.8
108  희망어린이공원        광주광역시 북구 두암동 564-1    2578.5
109  우리어린이공원        광주광역시 북구 우산동 602-1    1873.1

In [5]:
# 2) 경기도 데이터만 추출하세요.
gp.dropna(subset=['소재지지번주소'], inplace=True)
gp.isna().sum()

공원명        0
소재지지번주소    0
공원면적       0
dtype: int64

In [6]:
# 2) 경기도 데이터만 추출하세요.
gdf = gp[gp.소재지지번주소.str.contains('경기도')]
gdf.head(80).tail(10)

                   공원명               소재지지번주소      공원면적
429    제86호 어린이공원(한아름)   경기도 용인시 기흥구 상하동 631    1592.0
430  제49호 근린공원(김혁근린공원)   경기도 용인시 기흥구 구갈동 569   21920.0
431  제48호 근린공원(강남근린공원)   경기도 용인시 기흥구 구갈동 598  189796.0
432    제51호 어린이공원(하늘채)   경기도 용인시 기흥구 구갈동 549    1615.0
433     제52호 어린이공원(갈곡)   경기도 용인시 기흥구 구갈동 584    1501.0
434     제53호 어린이공원(강남)   경기도 용인시 기흥구 구갈동 602    1500.0
435    제54호 어린이공원(은하수)   경기도 용인시 기흥구 구갈동 605    1500.0
436    보정제1호 어린이공원(신촌)  경기도 용인시 기흥구 보정동 1201    1528.0
437    보정제2호 어린이공원(꽃메)  경기도 용인시 기흥구 보정동 1211    3324.0
438    보정제3호 어린이공원(독정)  경기도 용인시 기흥구 보정동 1235    3363.0

In [7]:
# 3) 소재지지번주소에서 시군구(예, 이천시, 양평군, 수원시 장안구)를 추출해서   시군구 컬럼을 만드세요.
gdf['시군구'] = gdf.소재지지번주소.apply(lambda x: ''.join(x.split()[1:3]) if x.find('구 ') >= 0 else x.split()[1])
gdf

                   공원명                소재지지번주소      공원면적     시군구
212              꿈나무공원         경기도 이천시 중리동 15    2526.0     이천시
213               남천공원        경기도 이천시 중리동 210    3830.0     이천시
214               향교공원        경기도 이천시 창전동 408    1757.0     이천시
215              개나리공원     경기도 이천시 창전동 414-13    1650.0     이천시
216              달맞이공원        경기도 이천시 창전동 423    1650.0     이천시
...                ...                    ...       ...     ...
17025  제90호 어린이공원(풀향기)    경기도 용인시 기흥구 중동 1083    1500.0  용인시기흥구
17258             청석공원        경기도 광주시 경안동 242  193530.0     광주시
17259           경안근린공원      경기도 광주시 경안동 168-1   83095.0     광주시
17260          삼리어린이공원  경기도 광주시 곤지암읍 삼리 131-1    1493.0     광주시
17261           중대물빛공원      경기도 광주시 중대동 246-2  230932.0     광주시

[4430 rows x 4 columns]

In [11]:
type(gp.공원면적[0])

numpy.float64

In [12]:
gdf.공원면적 = gdf.공원면적.astype(int)

In [13]:
# 4) 시군구 별로 공원면적의 합을 구하세요.
gdf1 = gdf.groupby(['시군구'])[['공원면적']].agg(['sum'])
gdf1.head()

            공원면적
             sum
시군구
가평군       511673
고양시덕양구   3287283
고양시일산동구  2722980
고양시일산서구   922486
과천시       315666

In [8]:
'''
1. 경기도 주민등록인구집계현황 파일을 읽고 다음에 답하세요. [40]
1) 행정구역구분명, 행정구역명, 총 인구수 컬럼만 선택해서 데이터프레임을   만드세요.
2) 경기도와 읍면동 인구를 제외한 시군과 구의 데이터만 추출하세요.   
(단, 양주시와 광주시 오포2동은 데이터를 고쳐서 사용하세요.) 
3) 수원시, 용인시 등 구가 있는 시는 시 데이터를 제거하세요.
4) 시군구 컬럼을 만드세요.
'''

'\n1. 경기도 주민등록인구집계현황 파일을 읽고 다음에 답하세요. [40]\n1) 행정구역구분명, 행정구역명, 총 인구수 컬럼만 선택해서 데이터프레임을   만드세요.\n2) 경기도와 읍면동 인구를 제외한 시군과 구의 데이터만 추출하세요.   \n(단, 양주시와 광주시 오포2동은 데이터를 고쳐서 사용하세요.) \n3) 수원시, 용인시 등 구가 있는 시는 시 데이터를 제거하세요.\n4) 시군구 컬럼을 만드세요.\n'

In [32]:
# 1) 행정구역구분명, 행정구역명, 총 인구수 컬럼만 선택해서 데이터프레임을   만드세요.
pop = pd.read_csv('../02.Pandas/data/주민등록인구집계현황.csv', encoding='euc-kr')
pop = pop[['행정구역구분명','행정구역명','총 인구수']]
pop.head()

  행정구역구분명        행정구역명     총 인구수
0       도        경기도    13589432
1      시군     경기도 가평군      62197
2     읍면동  경기도 가평군 가평읍     19555
3     읍면동   경기도 가평군 북면      3815
4     읍면동   경기도 가평군 상면      5669

In [ ]:
# 2) 경기도와 읍면동 인구를 제외한 시군과 구의 데이터만 추출하세요. 
# (단, 양주시와 광주시 오포2동은 데이터를 고쳐서 사용하세요.)

In [33]:
except_city = ['경기도 수원시', '경기도 고양시', '경기도 용인시', '경기도 성남시', '경기도 안산시', '경기도 안양시']

pop = pop[((pop.행정구역구분명 == '시군') | (pop.행정구역구분명 == '구')) & ~(pop['행정구역명'].str.strip().isin(except_city))]
pop

    행정구역구분명          행정구역명   총 인구수
1        시군       경기도 가평군    62197
9         구   경기도 고양시 덕양구   487874
31        구  경기도 고양시 일산동구   296590
44        구  경기도 고양시 일산서구   290738
56       시군       경기도 과천시    77775
63       시군       경기도 광명시   288182
83       시군       경기도 광주시   391704
100      시군       경기도 구리시   188876
109      시군       경기도 군포시   266531
122      시군       경기도 김포시   484194
137      시군      경기도 남양주시   737366
156      시군      경기도 동두천시    91735
165      시군       경기도 부천시   791263
177       구   경기도 성남시 분당구   482026
200       구   경기도 성남시 수정구   232125
218       구   경기도 성남시 중원구   206211
232       구   경기도 수원시 권선구   313834
245       구   경기도 수원시 영통구   495315
258       구   경기도 수원시 장안구   270524
269       구   경기도 수원시 팔달구   188701
280      시군       경기도 시흥시   512438
301       구   경기도 안산시 단원구   297509
314       구   경기도 안산시 상록구   345535
328      시군       경기도 안성시   189146
345       구   경기도 안양시 동안구   314102
363       구   경기도 안양시 만안구   234296
379      시군       경기도 양주시   241346
391      시군       경기도 양평군   122463
404      시군       경기도 여주시   113096
417      시군       경기도 연천군    42153
428      시군       경기도 오산시   229833
436       구   경기도 용인시 기흥구   438500
452       구   경기도 용인시 수지구   377198
464       구   경기도 용인시 처인구   259872
477      시군       경기도 의왕시   160464
484      시군      경기도 의정부시   463789
499      시군       경기도 이천시   223151
514      시군       경기도 파주시   494970
532      시군       경기도 평택시   577335
558      시군       경기도 포천시   147019
574      시군       경기도 하남시   325310
589      시군       경기도 화성시   907958

In [34]:
pop['시군구'] = pop.행정구역명.apply(lambda x: ''.join(x.split()[1:3]) if x.find('구 ') >= 0 else x.split()[1])
pop

    행정구역구분명          행정구역명   총 인구수      시군구
1        시군       경기도 가평군    62197      가평군
9         구   경기도 고양시 덕양구   487874   고양시덕양구
31        구  경기도 고양시 일산동구   296590  고양시일산동구
44        구  경기도 고양시 일산서구   290738  고양시일산서구
56       시군       경기도 과천시    77775      과천시
63       시군       경기도 광명시   288182      광명시
83       시군       경기도 광주시   391704      광주시
100      시군       경기도 구리시   188876      구리시
109      시군       경기도 군포시   266531      군포시
122      시군       경기도 김포시   484194      김포시
137      시군      경기도 남양주시   737366     남양주시
156      시군      경기도 동두천시    91735     동두천시
165      시군       경기도 부천시   791263      부천시
177       구   경기도 성남시 분당구   482026   성남시분당구
200       구   경기도 성남시 수정구   232125   성남시수정구
218       구   경기도 성남시 중원구   206211   성남시중원구
232       구   경기도 수원시 권선구   313834   수원시권선구
245       구   경기도 수원시 영통구   495315   수원시영통구
258       구   경기도 수원시 장안구   270524   수원시장안구
269       구   경기도 수원시 팔달구   188701   수원시팔달구
280      시군       경기도 시흥시   512438      시흥시
301       구   경기도 안산시 단원구   297509   안산시단원구
314       구   경기도 안산시 상록구   345535   안산시상록구
328      시군       경기도 안성시   189146      안성시
345       구   경기도 안양시 동안구   314102   안양시동안구
363       구   경기도 안양시 만안구   234296   안양시만안구
379      시군       경기도 양주시   241346      양주시
391      시군       경기도 양평군   122463      양평군
404      시군       경기도 여주시   113096      여주시
417      시군       경기도 연천군    42153      연천군
428      시군       경기도 오산시   229833      오산시
436       구   경기도 용인시 기흥구   438500   용인시기흥구
452       구   경기도 용인시 수지구   377198   용인시수지구
464       구   경기도 용인시 처인구   259872   용인시처인구
477      시군       경기도 의왕시   160464      의왕시
484      시군      경기도 의정부시   463789     의정부시
499      시군       경기도 이천시   223151      이천시
514      시군       경기도 파주시   494970      파주시
532      시군       경기도 평택시   577335      평택시
558      시군       경기도 포천시   147019      포천시
574      시군       경기도 하남시   325310      하남시
589      시군       경기도 화성시   907958      화성시

In [41]:
gdf1.reset_index(inplace=True)

In [47]:
gdf1.columns= ['시군구','공원면적']

In [ ]:
#  1, 2번에서 구한 데이터프레임을 합성한 후, 인당 공원면적을 구하세요. [20]

In [48]:
gdf1

        시군구     공원면적
0       가평군   511673
1    고양시덕양구  3287283
2   고양시일산동구  2722980
3   고양시일산서구   922486
4       과천시   315666
5       광명시  3397531
6       광주시   786478
7       구리시   912752
8       군포시  1455375
9       김포시  5792950
10     남양주시  4770408
11     동두천시  3649712
12      부천시  2920062
13   성남시분당구  7189160
14   성남시수정구  2018765
15   성남시중원구  1879871
16   수원시권선구  1383828
17   수원시영통구  4119775
18   수원시장안구   651618
19   수원시팔달구   917985
20      시흥시  4250221
21   안산시단원구  2860671
22   안산시상록구  3276706
23      안성시   880564
24   안양시동안구  1149033
25   안양시만안구   741237
26      양주시  2034792
27      양평군   687374
28      여주시   350087
29      연천군   237176
30      오산시  2271088
31   용인시기흥구  2678098
32   용인시수지구  1598214
33   용인시처인구  3105059
34      의왕시  2161446
35     의정부시  2249775
36      이천시  2025604
37      파주시  3820846
38      평택시  8095197
39      포천시  1825176
40      하남시  1676848
41      화성시  7339376

In [51]:
pop1 = pop[['시군구','총 인구수']]
pop1.reset_index(inplace=True)
pop1

    index      시군구   총 인구수
0       1      가평군   62197
1       9   고양시덕양구  487874
2      31  고양시일산동구  296590
3      44  고양시일산서구  290738
4      56      과천시   77775
5      63      광명시  288182
6      83      광주시  391704
7     100      구리시  188876
8     109      군포시  266531
9     122      김포시  484194
10    137     남양주시  737366
11    156     동두천시   91735
12    165      부천시  791263
13    177   성남시분당구  482026
14    200   성남시수정구  232125
15    218   성남시중원구  206211
16    232   수원시권선구  313834
17    245   수원시영통구  495315
18    258   수원시장안구  270524
19    269   수원시팔달구  188701
20    280      시흥시  512438
21    301   안산시단원구  297509
22    314   안산시상록구  345535
23    328      안성시  189146
24    345   안양시동안구  314102
25    363   안양시만안구  234296
26    379      양주시  241346
27    391      양평군  122463
28    404      여주시  113096
29    417      연천군   42153
30    428      오산시  229833
31    436   용인시기흥구  438500
32    452   용인시수지구  377198
33    464   용인시처인구  259872
34    477      의왕시  160464
35    484     의정부시  463789
36    499      이천시  223151
37    514      파주시  494970
38    532      평택시  577335
39    558      포천시  147019
40    574      하남시  325310
41    589      화성시  907958

In [52]:
del pop1['index']
pop1

        시군구   총 인구수
0       가평군   62197
1    고양시덕양구  487874
2   고양시일산동구  296590
3   고양시일산서구  290738
4       과천시   77775
5       광명시  288182
6       광주시  391704
7       구리시  188876
8       군포시  266531
9       김포시  484194
10     남양주시  737366
11     동두천시   91735
12      부천시  791263
13   성남시분당구  482026
14   성남시수정구  232125
15   성남시중원구  206211
16   수원시권선구  313834
17   수원시영통구  495315
18   수원시장안구  270524
19   수원시팔달구  188701
20      시흥시  512438
21   안산시단원구  297509
22   안산시상록구  345535
23      안성시  189146
24   안양시동안구  314102
25   안양시만안구  234296
26      양주시  241346
27      양평군  122463
28      여주시  113096
29      연천군   42153
30      오산시  229833
31   용인시기흥구  438500
32   용인시수지구  377198
33   용인시처인구  259872
34      의왕시  160464
35     의정부시  463789
36      이천시  223151
37      파주시  494970
38      평택시  577335
39      포천시  147019
40      하남시  325310
41      화성시  907958

In [53]:
df = pd.merge(gdf1, pop1)
df.set_index('시군구', inplace=True)
df

            공원면적   총 인구수
시군구
가평군       511673   62197
고양시덕양구   3287283  487874
고양시일산동구  2722980  296590
고양시일산서구   922486  290738
과천시       315666   77775
광명시      3397531  288182
광주시       786478  391704
구리시       912752  188876
군포시      1455375  266531
김포시      5792950  484194
남양주시     4770408  737366
동두천시     3649712   91735
부천시      2920062  791263
성남시분당구   7189160  482026
성남시수정구   2018765  232125
성남시중원구   1879871  206211
수원시권선구   1383828  313834
수원시영통구   4119775  495315
수원시장안구    651618  270524
수원시팔달구    917985  188701
시흥시      4250221  512438
안산시단원구   2860671  297509
안산시상록구   3276706  345535
안성시       880564  189146
안양시동안구   1149033  314102
안양시만안구    741237  234296
양주시      2034792  241346
양평군       687374  122463
여주시       350087  113096
연천군       237176   42153
오산시      2271088  229833
용인시기흥구   2678098  438500
용인시수지구   1598214  377198
용인시처인구   3105059  259872
의왕시      2161446  160464
의정부시     2249775  463789
이천시      2025604  223151
파주시      3820846  494970
평택시      8095197  577335
포천시      1825176  147019
하남시      1676848  325310
화성시      7339376  907958

In [55]:
df['인당공원면적'] = (df['총 인구수'] / df.공원면적 *100).round(2)
df

            공원면적   총 인구수  인당공원면적
시군구
가평군       511673   62197   12.16
고양시덕양구   3287283  487874   14.84
고양시일산동구  2722980  296590   10.89
고양시일산서구   922486  290738   31.52
과천시       315666   77775   24.64
광명시      3397531  288182    8.48
광주시       786478  391704   49.80
구리시       912752  188876   20.69
군포시      1455375  266531   18.31
김포시      5792950  484194    8.36
남양주시     4770408  737366   15.46
동두천시     3649712   91735    2.51
부천시      2920062  791263   27.10
성남시분당구   7189160  482026    6.70
성남시수정구   2018765  232125   11.50
성남시중원구   1879871  206211   10.97
수원시권선구   1383828  313834   22.68
수원시영통구   4119775  495315   12.02
수원시장안구    651618  270524   41.52
수원시팔달구    917985  188701   20.56
시흥시      4250221  512438   12.06
안산시단원구   2860671  297509   10.40
안산시상록구   3276706  345535   10.55
안성시       880564  189146   21.48
안양시동안구   1149033  314102   27.34
안양시만안구    741237  234296   31.61
양주시      2034792  241346   11.86
양평군       687374  122463   17.82
여주시       350087  113096   32.31
연천군       237176   42153   17.77
오산시      2271088  229833   10.12
용인시기흥구   2678098  438500   16.37
용인시수지구   1598214  377198   23.60
용인시처인구   3105059  259872    8.37
의왕시      2161446  160464    7.42
의정부시     2249775  463789   20.61
이천시      2025604  223151   11.02
파주시      3820846  494970   12.95
평택시      8095197  577335    7.13
포천시      1825176  147019    8.06
하남시      1676848  325310   19.40
화성시      7339376  907958   12.37