In [1]:
import numpy as np
import pandas as pd

In [2]:
filename = 'data/1서울시 자치구 년도별 CCTV 설치 현황_221231기준 (1).csv'
cctv = pd.read_csv(filename, encoding='euc-kr')
cctv.head()

,구분,총계,2013년 이전 설치된 CCTV,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년
0,계,"91,341","2,804","3,097","3,981","6,576","8,850","11,566","11,024","13,151","11,912","9,144","9,236"
1,종로구,"1,980",36,540,107,161,131,158,152,69,250,85,291
2,중 구,"2,584",130,87,77,236,240,372,386,155,361,403,137
3,용산구,"2,847",44,50,68,83,295,491,115,322,623,422,334
4,성동구,"4,047",58,99,110,366,279,945,459,647,485,367,232

In [3]:
# 총계
cctv['총계'] = cctv.총계.str.replace(',','').astype(int)
cctv.head()

,구분,총계,2013년 이전 설치된 CCTV,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년
0,계,91341,"2,804","3,097","3,981","6,576","8,850","11,566","11,024","13,151","11,912","9,144","9,236"
1,종로구,1980,36,540,107,161,131,158,152,69,250,85,291
2,중 구,2584,130,87,77,236,240,372,386,155,361,403,137
3,용산구,2847,44,50,68,83,295,491,115,322,623,422,334
4,성동구,4047,58,99,110,366,279,945,459,647,485,367,232

In [4]:
cctv.head()

,구분,총계,2013년 이전 설치된 CCTV,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년
0,계,91341,"2,804","3,097","3,981","6,576","8,850","11,566","11,024","13,151","11,912","9,144","9,236"
1,종로구,1980,36,540,107,161,131,158,152,69,250,85,291
2,중 구,2584,130,87,77,236,240,372,386,155,361,403,137
3,용산구,2847,44,50,68,83,295,491,115,322,623,422,334
4,성동구,4047,58,99,110,366,279,945,459,647,485,367,232

In [7]:
for i in cctv.index:
    print(cctv.구분[i], len(cctv.구분[i])) # 중 구 3 아마 바꿔줘야할듯 blank때문

계 1
종로구 3
중 구 3
용산구 3
성동구 3
광진구 3
동대문구 4
중랑구 3
성북구 3
강북구 3
도봉구 3
노원구 3
은평구 3
서대문구 4
마포구 3
양천구 3
강서구 3
구로구 3
금천구 3
영등포구 4
동작구 3
관악구 3
서초구 3
강남구 3
송파구 3
강동구 3

- 파일을 제대로 읽는 방법

In [5]:
cctv = pd.read_csv(filename, encoding='euc-kr', thousands=',')
# cctv = cctv[columns]
cctv.head()

,구분,총계,2013년 이전 설치된 CCTV,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년
0,계,91341,2804,3097,3981,6576,8850,11566,11024,13151,11912,9144,9236
1,종로구,1980,36,540,107,161,131,158,152,69,250,85,291
2,중 구,2584,130,87,77,236,240,372,386,155,361,403,137
3,용산구,2847,44,50,68,83,295,491,115,322,623,422,334
4,성동구,4047,58,99,110,366,279,945,459,647,485,367,232

In [12]:
type(cctv.총계[0])

numpy.int64