In [1]:
import numpy as np
import pandas as pd

In [2]:
filename = 'data/1서울시 자치구 년도별 CCTV 설치 현황_221231기준 (1).csv'
cctv = pd.read_csv(filename, encoding='euc-kr')
cctv.head()

,구분,총계,2013년 이전 설치된 CCTV,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년
0,계,"91,341","2,804","3,097","3,981","6,576","8,850","11,566","11,024","13,151","11,912","9,144","9,236"
1,종로구,"1,980",36,540,107,161,131,158,152,69,250,85,291
2,중 구,"2,584",130,87,77,236,240,372,386,155,361,403,137
3,용산구,"2,847",44,50,68,83,295,491,115,322,623,422,334
4,성동구,"4,047",58,99,110,366,279,945,459,647,485,367,232

In [3]:
# 총계
cctv['총계'] = cctv.총계.str.replace(',','').astype(int)
cctv.head()

,구분,총계,2013년 이전 설치된 CCTV,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년
0,계,91341,"2,804","3,097","3,981","6,576","8,850","11,566","11,024","13,151","11,912","9,144","9,236"
1,종로구,1980,36,540,107,161,131,158,152,69,250,85,291
2,중 구,2584,130,87,77,236,240,372,386,155,361,403,137
3,용산구,2847,44,50,68,83,295,491,115,322,623,422,334
4,성동구,4047,58,99,110,366,279,945,459,647,485,367,232

In [4]:
cctv.head()

,구분,총계,2013년 이전 설치된 CCTV,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년
0,계,91341,"2,804","3,097","3,981","6,576","8,850","11,566","11,024","13,151","11,912","9,144","9,236"
1,종로구,1980,36,540,107,161,131,158,152,69,250,85,291
2,중 구,2584,130,87,77,236,240,372,386,155,361,403,137
3,용산구,2847,44,50,68,83,295,491,115,322,623,422,334
4,성동구,4047,58,99,110,366,279,945,459,647,485,367,232

In [5]:
for i in cctv.index:
    print(cctv.구분[i], len(cctv.구분[i])) # 중 구 3 아마 바꿔줘야할듯 blank때문

계 1
종로구 3
중 구 3
용산구 3
성동구 3
광진구 3
동대문구 4
중랑구 3
성북구 3
강북구 3
도봉구 3
노원구 3
은평구 3
서대문구 4
마포구 3
양천구 3
강서구 3
구로구 3
금천구 3
영등포구 4
동작구 3
관악구 3
서초구 3
강남구 3
송파구 3
강동구 3

- 파일을 제대로 읽는 방법

In [19]:
cctv = pd.read_csv(filename, encoding='euc-kr', thousands=',')
# cctv = cctv[columns]
cctv.head()

,구분,총계,2013년 이전 설치된 CCTV,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년
0,계,91341,2804,3097,3981,6576,8850,11566,11024,13151,11912,9144,9236
1,종로구,1980,36,540,107,161,131,158,152,69,250,85,291
2,중 구,2584,130,87,77,236,240,372,386,155,361,403,137
3,용산구,2847,44,50,68,83,295,491,115,322,623,422,334
4,성동구,4047,58,99,110,366,279,945,459,647,485,367,232

In [7]:
'''
1. cctv 데이터를 다음과 같이 만들어 cctv.csv 파일에 저장하세요.

   구별    CCTV댓수  최근증가율

1 종로구 1715         20.69
2 중구    2447         78.98
3 용산구 2611          78.64

- 첫번째 행인 계는 삭제한다.
- 최근증가율은 최근 3개년간의 CCTV 댓수의 합을 그 이전 모든 년도의 CCTV 댓수의 합으로 나눈 값으로 백분율 값이다.
(2020+2021+2022)/(2013+2014+2015+2016+2017+2018+2019) *100
- 구별은 기존의 구분 열을 CCTV댓수는 기존의 총계 열을 이름만 변경한 것이다.
'''

'\n1. cctv 데이터를 다음과 같이 만들어 cctv.csv 파일에 저장하세요.\n\n   구별    CCTV댓수  최근증가율\n\n1 종로구 1715         20.69\n2 중구    2447         78.98\n3 용산구 2611          78.64\n\n- 첫번째 행인 계는 삭제한다.\n- 최근증가율은 최근 3개년간의 CCTV 댓수의 합을 그 이전 모든 년도의 CCTV 댓수의 합으로 나눈 값으로 백분율 값이다.\n(2020+2021+2022)/(2013+2014+2015+2016+2017+2018+2019) *100\n- 구별은 기존의 구분 열을 CCTV댓수는 기존의 총계 열을 이름만 변경한 것이다.\n'

In [20]:
cctv = cctv.drop(index=0,axis=0)
cctv.head()

,구분,총계,2013년 이전 설치된 CCTV,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년
1,종로구,1980,36,540,107,161,131,158,152,69,250,85,291
2,중 구,2584,130,87,77,236,240,372,386,155,361,403,137
3,용산구,2847,44,50,68,83,295,491,115,322,623,422,334
4,성동구,4047,58,99,110,366,279,945,459,647,485,367,232
5,광진구,3480,507,82,84,64,21,465,443,709,172,662,271

In [24]:
cctv['최근증가율'] = (((cctv['2020년']+cctv['2021년']+cctv['2022년'])\
                  /(cctv['2013년 이전 설치된 CCTV']+cctv['2013년']+cctv['2014년']+cctv['2015년']+cctv['2016년']+cctv['2017년']+cctv['2018년']+cctv['2019년'])) *100).round(2)
cctv.head(3)

,구분,총계,2013년 이전 설치된 CCTV,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년,최근증가율
1,종로구,1980,36,540,107,161,131,158,152,69,250,85,291,46.23
2,중 구,2584,130,87,77,236,240,372,386,155,361,403,137,53.54
3,용산구,2847,44,50,68,83,295,491,115,322,623,422,334,93.94

In [26]:
cctv.rename(columns={'구분': '자치구'})
cctv

,구분,총계,2013년 이전 설치된 CCTV,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년,최근증가율
1,종로구,1980,36,540,107,161,131,158,152,69,250,85,291,46.23
2,중 구,2584,130,87,77,236,240,372,386,155,361,403,137,53.54
3,용산구,2847,44,50,68,83,295,491,115,322,623,422,334,93.94
4,성동구,4047,58,99,110,366,279,945,459,647,485,367,232,36.58
5,광진구,3480,507,82,84,64,21,465,443,709,172,662,271,46.53
6,동대문구,2759,1,4,12,107,802,711,201,218,223,221,259,34.19
7,중랑구,4193,224,331,104,145,153,170,215,1074,976,507,294,73.55
8,성북구,4842,137,170,229,322,594,811,867,714,253,407,338,25.96
9,강북구,3321,0,21,16,68,210,4,375,963,569,298,797,100.42
10,도봉구,2247,103,2,79,72,103,117,200,202,183,600,586,155.92
11,노원구,2617,77,153,75,510,329,172,216,326,387,220,152,40.85
12,은평구,4653,17,44,332,329,555,403,635,1057,288,471,522,37.99
13,서대문구,3445,312,144,127,77,254,524,389,344,587,207,480,58.68
14,마포구,2628,21,40,109,170,458,376,368,494,298,177,117,29.08
15,양천구,3851,197,139,128,239,422,563,830,311,337,338,347,36.13
16,강서구,3265,67,59,202,193,168,506,259,458,359,439,555,70.76
17,구로구,4693,37,361,193,269,353,563,545,794,651,684,243,50.66
18,금천구,2636,0,0,43,361,133,196,539,367,513,207,277,60.83
19,영등포구,4553,109,81,295,360,285,422,803,153,1357,329,359,81.54
20,동작구,2671,66,25,502,127,256,271,300,307,432,30,355,44.07
21,관악구,5398,362,244,302,537,607,676,662,890,404,550,164,26.12
22,서초구,4995,74,86,70,559,518,1054,426,344,422,566,876,59.53
23,강남구,7243,59,62,573,826,1295,989,744,790,923,514,468,35.69
24,송파구,3203,84,78,88,221,163,256,516,1081,224,139,353,28.79
25,강동구,3190,82,195,56,174,226,351,379,362,635,301,429,74.79

In [22]:
cctv1 = cctv[['구분','총계','최근증가율']]
cctv1.head()

    구분    총계  최근증가율
1  종로구  1980  46.23
2  중 구  2584  53.54
3  용산구  2847  93.94
4  성동구  4047  36.58
5  광진구  3480  46.53

In [23]:
cctv1.columns

Index(['구분', '총계', '최근증가율'], dtype='object')

In [27]:
cctv1.rename(columns={'구분': '자치구'})
cctv1

      구분    총계   최근증가율
1    종로구  1980   46.23
2    중 구  2584   53.54
3    용산구  2847   93.94
4    성동구  4047   36.58
5    광진구  3480   46.53
6   동대문구  2759   34.19
7    중랑구  4193   73.55
8    성북구  4842   25.96
9    강북구  3321  100.42
10   도봉구  2247  155.92
11   노원구  2617   40.85
12   은평구  4653   37.99
13  서대문구  3445   58.68
14   마포구  2628   29.08
15   양천구  3851   36.13
16   강서구  3265   70.76
17   구로구  4693   50.66
18   금천구  2636   60.83
19  영등포구  4553   81.54
20   동작구  2671   44.07
21   관악구  5398   26.12
22   서초구  4995   59.53
23   강남구  7243   35.69
24   송파구  3203   28.79
25   강동구  3190   74.79

In [38]:
cctv1.rename(columns={
    '구분': '구별',
    '총계': 'CCTV갯수',
    '최근증가율': '최근 증가율'
}, inplace=True)

C:\Users\YONSAI\AppData\Local\Temp\ipykernel_12028\2757737334.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cctv1.rename(columns={

In [41]:
cctv2 = cctv1.head(3)
cctv2

    구별  CCTV댓수  최근 증가율
1  종로구    1980   46.23
2  중 구    2584   53.54
3  용산구    2847   93.94

In [ ]:
'''
2. 서울시 인구 데이터를 다음과 같이 만들어 pop.csv 파일에 저장하세요.

  구별     인구수  내국인  외국인  고령자  외국인비율  고령자비율
1 종로구 153789 144683  9106    27818   5.92           18.09
2 중구    131787 122499  9288    24392   7.05           18.51
3 용산구 237285 222953  14332   39070   6.04           16.47

- 첫번째 행인 합계는 삭제한다.
- 외국인비율은 외국인 수를 총 인구수로 나눈 백분율 값이다.
- 고령자비율은 65세 이상 인구 수를 총 인구수로 나눈 백분율 값이다.
'''

In [ ]:
# 이렇게 하니까 탭적용 가능 (파일내에서 확인함) 드래그시 공백한개
df.to_csv('data/test.tsv', sep='\t', index=False) # Pandas.to_csv(파일경로명)을 사용해 DataFrame을 CSV 파일로 저장

In [44]:
sp = pd.read('data/서울시인구.txt', encoding='utf-8')
sp

AttributeError: module 'pandas' has no attribute 'read'

In [48]:
with open('data/서울시인구.txt', 'r') as file:
    content = file.read()
print(content)

기간	자치구	세대	인구	인구	인구	인구	인구	인구	인구	인구	인구	세대당인구	65세이상고령자
기간	자치구	세대	합계	합계	합계	한국인	한국인	한국인	등록외국인	등록외국인	등록외국인	세대당인구	65세이상고령자
기간	자치구	세대	계	남자	여자	계	남자	여자	계	남자	여자	세대당인구	65세이상고령자
2021	합계	4,426,007	9,736,027	4,721,977	5,014,050	9,509,458	4,618,040	4,891,418	226,569	103,937	122,632	2.15	1,605,416
2021	종로구	73,494	153,789	74,186	79,603	144,683	70,183	74,500	9,106	4,003	5,103	1.97	27,818
2021	중구	63,519	131,787	64,083	67,704	122,499	59,630	62,869	9,288	4,453	4,835	1.93	24,392
2021	용산구	111,036	237,285	115,085	122,200	222,953	107,210	115,743	14,332	7,875	6,457	2.01	39,070
2021	성동구	134,233	292,672	142,259	150,413	285,990	139,380	146,610	6,682	2,879	3,803	2.13	46,380
2021	광진구	167,949	352,627	169,317	183,310	339,996	164,058	175,938	12,631	5,259	7,372	2.02	51,723
2021	동대문구	168,219	352,006	172,162	179,844	337,400	166,646	170,754	14,606	5,516	9,090	2.01	62,211
2021	중랑구	185,712	391,885	192,903	198,982	387,350	191,112	196,238	4,535	1,791	2,744	2.09	71,682
2021	성북구	195,017	440,142	211,150	228,992	430,528	207,578	222,950	9,614	3,572	6,042	2.21	74,709
2021	강북구	144,536	302,563	146,984	155,579	299,182	145,705	153,477	3,381	1,279	2,102	2.07	64,333
2021	도봉구	138,656	319,373	155,221	164,152	317,366	154,487	162,879	2,007	734	1,273	2.29	64,160
2021	노원구	217,378	514,946	247,813	267,133	510,956	246,053	264,903	3,990	1,760	2,230	2.35	88,345
2021	은평구	214,711	477,173	228,024	249,149	473,307	226,458	246,849	3,866	1,566	2,300	2.2	87,241
2021	서대문구	143,647	315,659	149,507	166,152	304,819	145,694	159,125	10,840	3,813	7,027	2.12	54,268
2021	마포구	179,861	378,686	177,233	201,453	368,905	173,504	195,401	9,781	3,729	6,052	2.05	54,582
2021	양천구	181,404	450,487	220,537	229,950	447,302	219,214	228,088	3,185	1,323	1,862	2.47	68,627
2021	강서구	271,175	579,768	278,720	301,048	574,315	276,292	298,023	5,453	2,428	3,025	2.12	92,558
2021	구로구	180,929	421,163	208,873	212,290	396,754	195,537	201,217	24,409	13,336	11,073	2.19	72,611
2021	금천구	117,595	244,891	124,110	120,781	230,811	116,527	114,284	14,080	7,583	6,497	1.96	41,041
2021	영등포구	187,020	400,908	198,740	202,168	376,837	185,926	190,911	24,071	12,814	11,257	2.01	62,516
2021	동작구	184,812	394,364	190,241	204,123	385,483	186,426	199,057	8,881	3,815	5,066	2.09	66,613
2021	관악구	276,597	499,449	250,058	249,391	485,699	243,991	241,708	13,750	6,067	7,683	1.76	79,871
2021	서초구	170,244	416,167	198,914	217,253	412,279	197,034	215,245	3,888	1,880	2,008	2.42	60,678
2021	강남구	234,233	537,800	257,280	280,520	533,042	255,047	277,995	4,758	2,233	2,525	2.28	78,226
2021	송파구	282,417	663,965	319,895	344,070	658,338	317,346	340,992	5,627	2,549	3,078	2.33	97,691
2021	강동구	201,613	466,472	228,682	237,790	462,664	227,002	235,662	3,808	1,680	2,128	2.29	74,070

In [55]:
옵션 찾아보기 skiprows =1 첫째줄무시하고 그다음부터 나오나그래ㅑㅐㅅ음
리스트안에 []row인덱스를 주면  찾아보기
header를 줄수도 있고 
read_csv 로 찾아보니가
ㄴ
pop = pd.read_csv('data/서울시인구.txt', sep='\t')  
pop.head()

,기간,자치구,세대,인구,인구.1,인구.2,인구.3,인구.4,인구.5,인구.6,인구.7,인구.8,세대당인구,65세이상고령자
0,기간,자치구,세대,합계,합계,합계,한국인,한국인,한국인,등록외국인,등록외국인,등록외국인,세대당인구,65세이상고령자
1,기간,자치구,세대,계,남자,여자,계,남자,여자,계,남자,여자,세대당인구,65세이상고령자
2,2021,합계,"4,426,007","9,736,027","4,721,977","5,014,050","9,509,458","4,618,040","4,891,418","226,569","103,937","122,632",2.15,"1,605,416"
3,2021,종로구,"73,494","153,789","74,186","79,603","144,683","70,183","74,500","9,106","4,003","5,103",1.97,"27,818"
4,2021,중구,"63,519","131,787","64,083","67,704","122,499","59,630","62,869","9,288","4,453","4,835",1.93,"24,392"

In [50]:
import csv

# txt 파일에서 데이터 추출하기
data = []
with open('data/서울시인구.txt', 'r') as f:
    lines = f.readlines()
    for line in lines:
        data.append(line.split('\t'))

# 추출한 데이터를 csv 파일에 저장하기
with open('data/서울시인구.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(data)

In [52]:
sp = pd.read_csv('data/서울시인구.csv', encoding='utf-8')
sp.head()

,기간,자치구,세대,인구,인구.1,인구.2,인구.3,인구.4,인구.5,인구.6,인구.7,인구.8,세대당인구,65세이상고령자\n
0,기간,자치구,세대,합계,합계,합계,한국인,한국인,한국인,등록외국인,등록외국인,등록외국인,세대당인구,65세이상고령자\n
1,기간,자치구,세대,계,남자,여자,계,남자,여자,계,남자,여자,세대당인구,65세이상고령자\n
2,2021,합계,"4,426,007","9,736,027","4,721,977","5,014,050","9,509,458","4,618,040","4,891,418","226,569","103,937","122,632",2.15,"1,605,416\n"
3,2021,종로구,"73,494","153,789","74,186","79,603","144,683","70,183","74,500","9,106","4,003","5,103",1.97,"27,818\n"
4,2021,중구,"63,519","131,787","64,083","67,704","122,499","59,630","62,869","9,288","4,453","4,835",1.93,"24,392\n"